export const SUBMIT_SIGNUP_DATA = 'SUBMIT_SIGNUP_DATA';
export const SUBMIT_VERIFICATION_TOKEN = 'SUBMIT_VERIFICATION_TOKEN';

export const SEND_SRP_VERIFIER = 'SEND_SRP_VERIFIER';
export const GET_SERVER_EPHEMERAL = 'GET_SERVER_EPHEMERAL';
export const LOGIN = 'LOGIN';
