export const VALID_SIGNUP_FORM_SUBMISSION = '@onepass/auth/VALID_SIGNUP_FORM_SUBMISSION';
export const VALID_VERIFICATION_TOKEN_SUBMISSION = '@onepass/auth/VALID_VERIFICATION_TOKEN_SUBMISSION';
export const USER_SIGNUP_SUCCEEDED = '@onepass/auth/USER_SIGNUP_SUCCEEDED';
export const ERROR_MESSAGE_RECEIVED = '@onepass/auth/ERROR_MESSAGE_RECEIVED';

export const GET_SERVER_AUTH_RESPONSE = '@onepass/auth/GET_SERVER_AUTH_RESPONSE';

export const USER_AUTH_SUCCEEDED = '@onepass/auth/USER_AUTH_SUCCEEDED';
export const USER_DE_AUTH_SUCCEEDED = '@onepass/auth/USER_DE_AUTH_SUCCEEDED';

export const FETCH_ENCRYPTION_KEYS = '@onepass/auth/FETCH_ENCRYPTION_KEYS';
